run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - gosec
    - misspell
    - nakedret
    - structcheck
    - typecheck
    - varcheck

issues:
  exclude-use-default: false

linters-settings:
  gofmt:
    simplify: true

  misspell:
    locale: US

  gosec:
    exclude:
      - G104 # Ignoring errors returned from functions

  errcheck:
    exclude-functions:
      - fmt.Printf
      - fmt.Println
      - fmt.Errorf
      - "(github.com/spf13/cobra.Command).Help"

output:
  format: colored-line-number
  sort-results: true
